### ISSUE TITLE
可以打印出未预料的错误吗，这样出了错后，可以定位到具体的行

### ISSUE THREAD

**Issue by vcxiaohan** [baryon/tracer#73]
比如：
`var a = b`
运行后，会报错：
```
ReferenceError: b is not defined
    at D:\hvb\passport\routes\user.js:35:10
    at Promise._execute (D:\hvb\passport\node_modules\_bluebird@3.5.0@bluebird\j
s\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (D:\hvb\passport\node_modules\_bluebird@3.5.
0@bluebird\js\release\promise.js:483:18)
    at new Promise (D:\hvb\passport\node_modules\_bluebird@3.5.0@bluebird\js\rel
ease\promise.js:79:10)
    at exports.add (D:\hvb\passport\routes\user.js:34:17)
    at Layer.handle [as handle_request] (D:\hvb\passport\node_modules\_express@4
.15.3@express\lib\router\layer.js:95:5)
    at next (D:\hvb\passport\node_modules\_express@4.15.3@express\lib\router\rou
te.js:137:13)
    at next (D:\hvb\passport\node_modules\_express@4.15.3@express\lib\router\rou
te.js:131:14)
```
这样项目上线后，我也能看日志快速定位问题，请问这个你有什么思路解决吗

**Comment by baryon** [comment]
use `try ... catch`
some refs
https://www.joyent.com/node-js/production/design/errors
https://stackoverflow.com/questions/7310521/node-js-best-practice-exception-handling
